2024-10-10 06:29:42 | INFO    | __main__:stash:131 | run - {'image': '20231121', 'version': '0.10.1.post2', 'role': 'EpicPlayer', 'headless': True}
2024-10-10 06:29:51 | INFO    | __main__:claim_epic_games:97 | Try to flush cookie - {'task': 'claim_epic_games'}
2024-10-10 06:29:53 | INFO    | epic_games.agent:_login:237 | login-with-email - {'url': 'https://www.epicgames.com/id/login?lang=en-US&noHostRedirect=true&redirectUrl=https://store.epicgames.com/en-US/free-games&__cf_chl_rt_tk=8_EeGgHt0GPuCwmGUvRGt6KejB5s3Pmv7N_lWQ3Og3c-1728512993-1.0.1.1-RvBGHPUEFany3SR4zexmSuYbIvId3939PZmWX8Tzsgg'}
2024-10-10 06:30:23 | WARNING    | epic_games.agent:authorize:266 | 执行超时 - {'task': 'authorize', 'retry': 0}
2024-10-10 06:30:26 | INFO    | epic_games.agent:_login:237 | login-with-email - {'url': 'https://www.epicgames.com/id/login?lang=en-US&noHostRedirect=true&redirectUrl=https://store.epicgames.com/en-US/free-games&__cf_chl_rt_tk=pTJMsLkumxh1bAkE_xkv8rCpBRaSYkkTPm4UJrCSuWE-1728513026-1.0.1.1-QKPvTIUYWONIIN__y_DhonEWAAWzkkngKdY3VWR_41A'}
2024-10-10 06:30:56 | WARNING    | epic_games.agent:authorize:266 | 执行超时 - {'task': 'authorize', 'retry': 1}
2024-10-10 06:30:59 | INFO    | epic_games.agent:_login:237 | login-with-email - {'url': 'https://www.epicgames.com/id/login?lang=en-US&noHostRedirect=true&redirectUrl=https://store.epicgames.com/en-US/free-games&__cf_chl_rt_tk=yuTB5821hCjhQb8pf8Lvvam5lHse.djgY1l0aWH6sl4-1728513059-1.0.1.1-ChtqlKueF8S8YCLci7G_Hn0v9b1uCzK5O5wSmtar94w'}
2024-10-10 06:31:29 | WARNING    | epic_games.agent:authorize:266 | 执行超时 - {'task': 'authorize', 'retry': 2}
2024-10-10 06:31:29 | ERROR    | __main__:run:158 | An error has been caught in function 'run', process 'MainProcess' (3736), thread 'MainThread' (140305878076288): - {}
Traceback (most recent call last):
  File "/home/runner/work/free-epic/free-epic/epic/src/claim.py", line 162, in <module>
    asyncio.run(run())
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/home/runner/work/free-epic/free-epic/epic/src/claim.py", line 158, in run
    await agent.stash()
  File "/home/runner/work/free-epic/free-epic/epic/src/claim.py", line 151, in stash
    await self.claim_epic_games(context)
  File "/home/runner/work/free-epic/free-epic/epic/src/claim.py", line 98, in claim_epic_games
    if await epic.authorize(page):
  File "/home/runner/work/free-epic/free-epic/epic/src/epic_games/agent.py", line 269, in authorize
    raise RuntimeError(f"Failed to flush token - agent={self.__class__.__name__}")
RuntimeError: Failed to flush token - agent=EpicGames
